[output]
path="/home/bobguo/generate_data"
fileprefix="2022-01-01"

[base]
#Configure  table list  and column  list
tables="test.t,test.t1"
columns="test.t.a,"

[join]
#Configure the association between tables

[check]
#Specify column limits, max and min values, and list of values

