#This file as Config struct

#Out put file 
[Output]
path = "./"
fileprefix = "111"

#Configure  table list  and column  list
[Tables]
tables = "test.t,test.t1"
ignorecolumns = ""


#Configure join column list
[Join]
relationship = "test.t.ID/test.t1.ID/5,test.t.Name/test.t1.Name/5"

#Specify column limits, max and min values, and list of values
#example 1: column val list 
#example 2: colume val range 
[Check]
rule = "test.t.ID:1~1000000" 


#base table 
[Base]
table = "test.t"
rowcount = "100000"
#unit :M
peerfilesize = "100"
#unit :Rows
peerfilenum = "5000"
#thread pool size 
threadpoolsize = "30"

#DSN : connect to database get meta data
dsn = "root:root@tcp(172.16.4.155:4000)/zdjx"
#record desc 
fieldterm = "\t"
lineterm = "\n"

